CREATE TABLE worklog (
  id INTEGER PRIMARY KEY NOT NULL,
  created_at VARCHAR NOT NULL DEFAULT CURRENT_TIMESTAMP,
  description VARCHAR NOT NULL
);

CREATE TABLE tags (
  id INTEGER PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL
);

CREATE TABLE tag_keywords (
  id INTEGER PRIMARY KEY NOT NULL,
  keyword VARCHAR NOT NULL, 
  tag_id INTEGER NOT NULL,
  FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE work_tags (
  work_id INTEGER NOT NULL,
  tag_id INTEGER NOT NULL,
  FOREIGN KEY(work_id) REFERENCES worklog(id),
  FOREIGN KEY(tag_id) REFERENCES tags(id),
  PRIMARY KEY(work_id, tag_id)
);
